### ISSUE TITLE
Ability to mark a patient contact as an emergency contact

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect-fhir#1]
This issue was originally raised by Microtest and relates to how the Patient profile has had the Patient.contact.relationship redefined in the DMS.

Please see;

http://hl7.org/fhir/DSTU2/patient-definitions.html#Patient.contact.relationship

In DSTU2 this uses (which is an Extensible binding);

http://hl7.org/fhir/DSTU2/valueset-patient-contact-relationship.html

However, it has been redefined in our profiles to bind to;

http://data.developer.nhs.uk/fhir/candidaterelease-170816-getrecord/Profile.GetRecordQueryResponse-HTMLView/cda-person-relationship-type-1.html

**Comment by michaelmeasures** [comment]
It seems there should be an "Emergency" option in the valueset, like in the standard fhir valueset, but we will need to go with "unknown" for FoT entry.

**Comment by jonnyry** [comment]
In STU3 the Patient.contact.relationship now binds only to the FHIR international default including the value "Emergency Contact":

https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Patient-1
